#!/bin/sh

# Network and LuCI defaults (branding in 98-jas0n0ss-branding)

uci set network.lan.ipaddr='10.10.10.1'
uci set network.lan.netmask='255.255.255.0'
uci commit network

uci set dhcp.lan.start='100'
uci set dhcp.lan.limit='150'
uci set dhcp.lan.leasetime='12h'
uci commit dhcp

uci set luci.main.mediaurlbase='/luci-static/aurora'
uci commit luci

cat > /etc/ssh/sshd_config.d/99-welcome << 'EOF'
Banner /etc/banner
EOF

cat >> /etc/sysctl.conf << 'EOF'
net.core.rmem_default=262144
net.core.wmem_default=262144
net.core.rmem_max=16777216
net.core.wmem_max=16777216
net.ipv4.tcp_congestion_control=bbr
net.core.default_qdisc=fq
EOF

exit 0
